## Manually expands what load_enu_script would generate for:
##   import position_c_tree
##   load_enu_script "forest_script.nim", Build, drawing, draw_position
## where forest_script.nim is:
##   Tree.new(height = 5, position = vec3(35, 0, -20))
##   Tree.new(height = 8, canopy_color = blue, position = vec3(40, 0, -25))
##   Tree.new(height = 4, trunk_color = red, position = vec3(32, 0, -28))
##
## This mirrors the cross-module scenario where Tree.new was already compiled
## in position_c_tree, so vmgen's genProc hits the else-branch when compiling
## the Tree.new calls here.

import std/[tables]
import types, state_machine, base_api, base_bridge, builds
import position_c_tree

var test_unit2 = Unit()
test_unit2.query_results = initTable[string, seq[Unit]]()
register_active(test_unit2)

let me2 = Build()

# run_script generated by load_enu_script (forest version)
proc run_forest(me: Build, is_instance: bool) =
  var enu_target: Unit = me
  let home = PositionOffset(position: me.local_position)
  var move_mode = 1
  # include loops (inlined):
  var loop_context: Context = nil
  me.advance_state_machine =
    proc(): bool =
      result =
        if not loop_context.is_nil:
          loop_context.advance()
        else:
          true
  proc loop_started(ctx: Context, main_loop: bool) =
    if main_loop:
      loop_context = ctx
  proc loop_ended(ctx: Context, main_loop: bool) =
    if main_loop:
      loop_context = nil
  # script body (auto_insert_receiver applied):
  Tree.new(height = 5, position = vec3(35, 0, -20))
  Tree.new(height = 8, canopy_color = blue, position = vec3(40, 0, -25))
  Tree.new(height = 4, trunk_color = red, position = vec3(32, 0, -28))
  sleep 0.0

run_forest(me2, false)
echo "position_d_forest: passed"
