## Manually expands what load_enu_script would generate for:
##   load_enu_script "tree_class.nim", Build, drawing, draw_position
## where tree_class.nim is:
##   name Tree(height = 6, trunk_color = brown, canopy_color = green)
##   if not is_instance: quit()

import std/[tables]
import types, state_machine, base_api, base_bridge, builds

var test_unit = Unit()
test_unit.query_results = initTable[string, seq[Unit]]()
register_active(test_unit)

# Type generated by build_class
type TreeType* = ref object of Build
  height*: int
  trunk_color*: Colors
  canopy_color*: Colors

# Accessor procs generated by params_to_accessors
proc tree_height*(self: TreeType): int = self.height
proc `tree_height=`*(self: TreeType, value: int) =
  if value != self.height:
    self.height = value
    self.wake

proc tree_trunk_color*(self: TreeType): Colors = self.trunk_color
proc `tree_trunk_color=`*(self: TreeType, value: Colors) =
  if value != self.trunk_color:
    self.trunk_color = value
    self.wake

proc tree_canopy_color*(self: TreeType): Colors = self.canopy_color
proc `tree_canopy_color=`*(self: TreeType, value: Colors) =
  if value != self.canopy_color:
    self.canopy_color = value
    self.wake

# Module-level vars generated by build_class
let me* {.inject.} = TreeType()
var enu_target* {.inject.}: Unit = me
let Tree* {.inject.} = me

# Constructor generated by build_ctors
proc new*(
    instance: TreeType,
    height = 6,
    trunk_color = brown,
    canopy_color = green,
    global = false,
    speed = 1.0,
    color = eraser,
    position = UNSET_POSITION,
): TreeType {.discardable.} =
  assert not instance.is_nil
  result = TreeType()
  result.seed = active_unit().seed
  new_instance(instance, result)
  result.height = height
  result.trunk_color = trunk_color
  result.canopy_color = canopy_color
  result.global = global
  result.speed = speed
  if color != eraser:
    result.color = color
  apply_position(result, position)
  exec_instance(result)

# run_script generated by load_enu_script (tree class version)
proc run_script*(
    me {.inject.}: TreeType, is_instance {.inject.}: bool
) =
  var enu_target {.inject.}: Unit = me
  let home {.inject.} = PositionOffset(position: me.local_position)
  var move_mode {.inject.} = 1
  # include loops (inlined):
  var loop_context: Context = nil
  me.advance_state_machine =
    proc(): bool =
      result =
        if not loop_context.is_nil:
          loop_context.advance()
        else:
          true
  proc loop_started(ctx: Context, main_loop: bool) =
    if main_loop:
      loop_context = ctx
  proc loop_ended(ctx: Context, main_loop: bool) =
    if main_loop:
      loop_context = nil
  # params_to_assignments (only when !is_instance, to set defaults):
  if not is_instance:
    me.height = 6
    me.trunk_color = brown
    me.canopy_color = green
  # script body:
  if not is_instance:
    enu_target.show = false
    base_api.quit()
  sleep 0.0

run_script(me, false)
echo "position_c_tree: class defined"
