# AUTOGENERATED
# This file is managed by Enu. Delete the line above to manage it yourself.
version = "0.1.0"
author = "Enu"
description = "Enu world scripts"
license = "MIT"
srcDir = "."
bin = @["project"]
