import
  std/[
    json, jsonutils, sugar, tables, strutils, strformat, os, times, algorithm,
    math, sets,
  ]
import pkg/zippy/ziparchives_v1
import core except to_json
import models
import models/voxels
import controllers/script_controllers/scripting
import controllers/script_controllers/vars
import libs/eval

proc to_json_hook(self: Vector3): JsonNode =
  %[self.x, self.y, self.z]

proc from_json_hook(self: var Vector3, json: JsonNode) =
  self.x = json[0].get_float
  self.y = json[1].get_float
  self.z = json[2].get_float

proc from_json_hook(self: var Transform, json: JsonNode) =
  self = Transform.init(origin = json["origin"].json_to(Vector3))
  let elements =
    if json["basis"].kind == JObject:
      # old way
      json["basis"]["elements"]
    else:
      # new way
      json["basis"]
  self.basis.elements.from_json(elements)

proc to_json_hook(self: Transform): JsonNode =
  %*{
    "basis": self.basis.elements.map_it(%[it.x, it.y, it.z]),
    "origin": self.origin.to_json_hook,
  }

const PLAYERS_SENTINEL* = "PLAYERS"
  ## load_order sentinel, not a unit: the units before it must render before
  ## players are handed control (the spawn gate). Always present — auto
  ## inserted at the front when missing, which means "nothing to wait for":
  ## immediate physics at start_transform, no splash.

type LevelInfo = object
  format_version*: string
  load_order*: seq[string]
  show_prototypes*: bool
  show_tools*: bool
  start_transform*: Transform

proc from_json_hook*(self: var LevelInfo, json: JsonNode) =
  self.format_version = json{"format_version"}.get_str

  if "load_order" in json:
    self.load_order = json["load_order"].json_to(seq[string])
  else:
    self.load_order = @[]

  if "show_prototypes" in json:
    self.show_prototypes = json["show_prototypes"].get_bool
  else:
    self.show_prototypes = true

  if "show_tools" in json:
    self.show_tools = json["show_tools"].get_bool
  else:
    self.show_tools = true

  if "start_transform" in json:
    self.start_transform = json["start_transform"].json_to(Transform)
  else:
    self.start_transform = Transform.init(origin = vec3(0, 1, 0))

type WorldInfo = object
  ## world.json — committed, hand-editable world metadata that lives at the
  ## world root (the git unit). For now it only names the level Enu opens when
  ## no level is requested. Unlike CLAUDE.md it carries no AUTOGENERATED marker:
  ## Enu creates it once when a world has none and never rewrites it.
  initial_level*: string

proc from_json_hook*(self: var WorldInfo, json: JsonNode) =
  self.initial_level = json{"initial_level"}.get_str

proc to_json_hook*(self: VoxelInfo): JsonNode =
  %[%self.kind.ord, self.color.to_json_hook]

proc from_json_hook*(self: var VoxelInfo, json: JsonNode) =
  self.kind = VoxelKind(json[0].get_int)
  self.color = json[1].json_to(Color)

proc load_frames_sidecar*(self: Build, json: JsonNode) =
  let meta = json["frames"]
  let dir = self.data_dir / "frames"
  let count = meta["count"].get_int
  var prev = none(FrameData)
  var loaded = 0
  for i in 0 ..< count:
    let path = dir / \"{i:03}.bin"
    if not file_exists(path):
      warn "frame sidecar file missing; dropping later frames",
        unit = self.id, frame = i
      break
    try:
      let frame = decode_frame_file(read_file(path), prev)
      self.frames[i] = frame
      prev = some(frame)
      inc loaded
    except ValueError as e:
      warn "frame sidecar file unreadable; dropping later frames",
        unit = self.id, frame = i, error = e.msg
      break
  self.reset_bounds() # frame chunks count toward bounds (see reset_bounds)
  self.frames_dirty = false # loaded verbatim from disk; nothing to re-save
  info "frames sidecar loaded", unit = self.id, loaded = loaded
  if loaded > 0:
    # Playback is never auto-resumed — it's a runtime action a script
    # triggers with `play()`. Show the first frame so the unit comes back
    # visible (its voxels are TRANSIENT, so only frames survive on
    # reload); a script then takes over if it plays. fps/loop/current are
    # no longer persisted (script-driven state — see extras_json).
    self.current_frame = 0

proc from_json_hook(self: var Build, json: JsonNode) =
  let color = json["start_color"].json_to(Color)
  self = Build.init(
    id = json["id"].json_to(string),
    transform = json["start_transform"].json_to(Transform),
    color = color,
  )

  if "palette" in json:
    # Restore the static palette in saved order BEFORE anything packs a
    # color: frame files (and future binary edits) reference palette
    # indices, so the sequence must match the one they were written with.
    for entry in json["palette"]:
      discard pack_color_index(self.shared, entry.json_to(Color))

  if "edits_file" in json:
    # big-build sidecar: packed chunks stored directly (palette already
    # restored above, so the indices inside resolve)
    let path = self.data_dir / json["edits_file"].json_to(string)
    if file_exists(path):
      for thing_id, chunks in decode_edits_file(read_file(path)):
        for chunk_id, snapshot in chunks:
          self.shared.edit_snapshots[(thing_id, chunk_id)] = snapshot
    else:
      warn "edits sidecar missing", unit = self.id, path = path
  elif "edits" in json:
    for id, edits in json["edits"]:
      var current_chunk_edits: seq[(Vector3, VoxelInfo)] = @[]
      for edit in edits:
        let world_pos = edit[0].json_to(Vector3)
        let info = edit[1].json_to(VoxelInfo)
        current_chunk_edits.add((world_pos, info))

      if current_chunk_edits.len > 0:
        self.shared.pack_and_store_edited_voxels(id, current_chunk_edits)

  self.voxels.rebuild_local_edits()

  if "frames" in json:
    self.load_frames_sidecar(json)

proc from_json_hook(self: var Bot, json: JsonNode) =
  # `start_color` is always written (the shared thing serializer), but tolerate
  # hand-authored or ancient files that lack it.
  let color =
    if "start_color" in json:
      json["start_color"].json_to(Color)
    else:
      ACTION_COLORS[BLACK]
  self = Bot.init(
    id = json["id"].json_to(string),
    transform = json["start_transform"].json_to(Transform),
    color = color,
  )

  if "palette" in json:
    for entry in json["palette"]:
      discard pack_color_index(self.shared, entry.json_to(Color))

  if "edits_file" in json:
    let path = self.data_dir / json["edits_file"].json_to(string)
    if file_exists(path):
      for thing_id, chunks in decode_edits_file(read_file(path)):
        for chunk_id, snapshot in chunks:
          self.shared.edit_snapshots[(thing_id, chunk_id)] = snapshot
    else:
      warn "edits sidecar missing", unit = self.id, path = path
  elif "edits" in json:
    for id, edits in json["edits"]:
      var current_chunk_edits: seq[(Vector3, VoxelInfo)] = @[]
      for edit in edits:
        let world_pos = edit[0].json_to(Vector3)
        let info = edit[1].json_to(VoxelInfo)
        current_chunk_edits.add((world_pos, info))

      if current_chunk_edits.len > 0:
        self.shared.pack_and_store_edited_voxels(id, current_chunk_edits)

proc `$`(self: Color): string =
  $json_utils.to_json(self)

proc `$`(self: VoxelInfo): string =
  \"[{self.kind.ord}, \"{self.color}\"]"

proc `$`(self: tuple[voxel: Vector3, info: VoxelInfo]): string =
  \"[{$[self.voxel.x, self.voxel.y, self.voxel.z]}, [{int self.info.kind}, {self.info.color}]]"

proc edits_to_string(shared: Shared): string =
  ## Serialize edit_snapshots to JSON format for backwards compatibility
  # Group edits by thing_id
  var by_thing: Table[string, seq[tuple[pos: Vector3, info: VoxelInfo]]]

  for key, packed in shared.edit_snapshots.value:
    let thing_id = key.id
    let chunk_id = key.loc

    let decoded = decode_chunk(packed)
    for linear in 0 ..< CHUNK_VOLUME:
      let packed_voxel = decoded[linear]
      if packed_voxel != EMPTY_VOXEL:
        let (color_idx, kind_ord) = unpack_voxel(packed_voxel)
        let local_pos = from_linear(linear)
        # Convert to world position
        let world_pos = vec3(
          chunk_id.x * ChunkDim + local_pos.x,
          chunk_id.y * ChunkDim + local_pos.y,
          chunk_id.z * ChunkDim + local_pos.z,
        )
        let info = (VoxelKind(kind_ord), resolve_color(shared, color_idx))
        if thing_id notin by_thing:
          by_thing[thing_id] = @[]
        by_thing[thing_id].add((world_pos, info))

  # Format output
  let edits = collect:
    for thing_id, voxels in by_thing:
      let json = voxels.map_it($(it.pos, it.info))
      if json.len > 0:
        let elements = json.join(",\n").indent(2)
        \"\"{thing_id}\": [\n{elements}\n]"
  result = edits.join(",\n")

proc count_frame_files(dir: string): int =
  for kind, path in walk_dir(dir):
    if kind == pcFile and path.ends_with(".bin"):
      inc result

proc save_frames(self: Build) =
  ## Frame animation sidecar: data/<id>/frames/NNN.bin, keyframes every
  ## FRAME_KEYFRAME_INTERVAL frames and per-chunk deltas between. The unit
  ## JSON carries the metadata (count, fps, loop) and the static palette
  ## the packed values reference.
  let dir = self.data_dir / "frames"
  if self.frames.len == 0:
    if dir_exists(dir):
      remove_dir(dir)
    return
  if not self.frames_dirty and dir_exists(dir) and
      count_frame_files(dir) == self.frames.len:
    # Untouched since load/last save: skip 24 frame re-encodes per save.
    # (Local frame mutations set frames_dirty; client-synced frames are
    # covered by the dir/count checks — a same-count in-place replacement
    # from a remote client is the one uncovered case, and the generator
    # workflow always starts from a deleted data dir.)
    return
  create_dir dir
  var prev = none(FrameData)
  for i in 0 ..< self.frames.len:
    let frame = self.frames[i]
    let key = i mod FRAME_KEYFRAME_INTERVAL == 0
    let data = encode_frame_file(
      frame,
      if key: none(FrameData) else: prev
    )
    write_file_if_changed(dir / \"{i:03}.bin", data)
    prev = some(frame)
  for kind, path in walk_dir(dir):
    if kind == pcFile and path.ends_with(".bin"):
      let name = path.extract_filename
      var stale = true
      try:
        let idx = parse_int(name[0 ..^ 5])
        stale = idx < 0 or idx >= self.frames.len
      except ValueError:
        discard
      if stale:
        remove_file path
  self.frames_dirty = false

proc extras_json(self: Thing): string =
  ## Optional trailing sections for the unit JSON: frame-animation metadata
  ## and the static color palette (frame files reference palette indices,
  ## so the palette must restore in the same order on load).
  if self of Build and Build(self).frames.len > 0:
    let build = Build(self)
    # Format metadata only. Playback state — fps, loop, and the current
    # frame — is driven by the script's `play()` and must not persist: the
    # live playhead churned the JSON on every save, and re-running the
    # script re-establishes how the animation plays.
    result.add \""",
  "frames": {{
    "version": {FRAME_FILE_VERSION},
    "count": {build.frames.len},
    "keyframe_interval": {FRAME_KEYFRAME_INTERVAL}
  }}"""
  if ?self.shared and self.shared.palette.len > 0:
    # One color per line: a gradient build's palette runs to hundreds of
    # entries, and a single wrapped line is unreadable / undiffable.
    let entries = collect:
      for color in self.shared.palette:
        \"    {$color}"
    result.add \""",
  "palette": [
{entries.join(",\n")}
  ]"""

proc edited_voxel_count(shared: Shared): int =
  for _, packed in shared.edit_snapshots.value:
    let decoded = decode_chunk(packed)
    for linear in 0 ..< CHUNK_VOLUME:
      if decoded[linear] != EMPTY_VOXEL:
        inc result

proc save_edits_sidecar(self: Thing): bool =
  ## Big builds persist their hand edits as packed chunks in
  ## data/<id>/edits.bin instead of the per-voxel JSON list (~30-40x
  ## smaller before compression). Returns whether the sidecar was written
  ## — the JSON then records "edits_file" instead of inline edits.
  if state.is_nil or not state.config_value.loaded:
    # No level dir (bare `$unit`, e.g. a unit test with no game state) —
    # there's nowhere to write a sidecar, so keep edits inline and touch no
    # files. `data_dir` dereferences `state.config`, absent here.
    return false
  if edited_voxel_count(self.shared) <= EDITS_SIDECAR_THRESHOLD:
    let stale = self.data_dir / "edits.bin"
    if file_exists(stale):
      remove_file stale
    return false
  var edits: Table[string, Table[Vector3, SnapshotData]]
  for key, packed in self.shared.edit_snapshots.value:
    edits.mget_or_put(key.id, Table[Vector3, SnapshotData]())[key.loc] = packed
  create_dir self.data_dir
  write_file_if_changed(self.data_dir / "edits.bin", encode_edits_file(edits))
  true

proc `$`(self: Thing): string =
  let elements =
    self.start_transform.basis.elements.map_it($[it.x, it.y, it.z]).join(",\n")
  let origin = self.start_transform.origin
  let edits_section =
    if self.save_edits_sidecar():
      "\"edits_file\": \"edits.bin\""
    else:
      let edits = edits_to_string(self.shared)
      \""""edits": {{
{edits.indent(4)}
  }}"""
  result = \"""
{{
  "id": "{self.id}",
  "start_transform": {{
    "basis": [
{elements.indent(6)}
    ],
    "origin": {$[origin.x, origin.y, origin.z]}
  }},
  "start_color": {self.start_color},
  {edits_section}{self.extras_json}
}}
    """

proc save*(thing: Thing) =
  if not ?thing.clone_of:
    if thing of Build:
      Build(thing).voxels.flush_edits_for_save()

    let data =
      if thing of Build or thing of Bot:
        $thing
      else:
        return
    # Things are marked DIRTY at init, so freshly-deserialized things get
    # re-saved verbatim on the next save_level; write_file_if_changed keeps
    # that from bumping the mtime and reload-looping another instance
    # watching the same level dir.
    create_dir thing.data_dir
    write_file_if_changed(thing.data_file, data)
    if thing of Build:
      Build(thing).save_frames()

    for thing in thing.things:
      thing.save

proc topo_sort(
    nodes: seq[string], graph: Table[string, seq[string]]
): seq[string] =
  var
    visited = initHashSet[string]()
    temp_visited = initHashSet[string]()
    order = newSeq[string]()

  proc visit(node: string) =
    if node in temp_visited:
      raise ValueError.init(
        "Circular dependency detected involving script: " & node
      )
    if node in visited:
      return

    temp_visited.incl(node)

    if node in graph:
      for dep_path in graph[node]:
        visit(dep_path.extract_filename)

    temp_visited.excl(node)
    visited.incl(node)
    order.add(node)

  for node in nodes:
    visit(node)

  result = order

proc load_things*(parent: Thing, load_order: seq[string] = newSeq[string]()) =
  let opts = JOptions(allow_missing_keys: true)
  let path = if ?parent: parent.data_dir else: state.config.data_dir

  var loaded_data:
    seq[tuple[id: string, dir: string, json: JsonNode, script: string]] = @[]
  var sort_nodes = newSeq[string]()
  var script_to_data = initTable[string, int]()

  for dir in walk_dirs(path / "*"):
    let thing_id = dir.split_path.tail
    let file_name = dir / thing_id & ".json"
    if not file_exists(file_name):
      continue

    try:
      let data_file = read_file(file_name).parse_json
      let script_name = thing_id
      loaded_data.add((thing_id, dir, data_file, script_name))
      # players.nim is loaded separately or always first, so exclude it from
      # the dependency graph sort to avoid circular dependency issues or
      # confusion.
      if script_name != "players":
        sort_nodes.add(script_name)
      script_to_data[script_name] = loaded_data.high
    except Exception as e:
      error "Failed to read thing file", thing_id, error = e

  var sorted_scripts = load_order

  # Things missing from the saved list get slotted in. Only a gating level —
  # one whose PLAYERS sentinel sits past the front — pulls script-less data
  # units (the terrain and other pure-JSON builds the player needs underfoot)
  # ahead of the gate; unlisted scripted things always append at the end. With
  # no gate (PLAYERS first, including a level that had no sentinel and got one
  # forced to the front) everything appends, so PLAYERS stays first and nothing
  # loads ahead of the reveal.
  let gating = sorted_scripts.find(PLAYERS_SENTINEL) > 0
  for (id, dir, _, script) in loaded_data:
    if script notin sorted_scripts:
      let script_less =
        not file_exists(state.config.script_dir / script & ".nim") and
        not file_exists(dir / script & ".nim")
      if gating and script_less:
        sorted_scripts.insert(script, 0)
      else:
        sorted_scripts.add script

  # One-phase load, in load_order: each unit loads COMPLETELY — data, frame
  # sidecar, script — before the next one starts. Dependencies are the list
  # order, nothing more: a script that references a later unit's proto fails
  # into failed_scripts and retries once the level is up, and the recorded
  # load_order self-heals for the next boot. The PLAYERS sentinel is the
  # reveal point: everything before it is fully loaded and RUNNING behind
  # the splash, so the gate (game.nim) releases onto a settled, animating
  # world while the rest of the list streams in behind the player.
  for script_name in sorted_scripts:
    if script_name == PLAYERS_SENTINEL:
      # The reveal step, not a unit. Clear the synced splash-phase signal —
      # each main thread reveals once its own copy of the pre-PLAYERS units
      # reports rendered. (The players were already carried to
      # start_transform at load start, so the spawn area has been streaming
      # at top viewer priority the whole time.)
      if parent.is_nil:
        info "spawn gate: PLAYERS step, clearing LOAD_SCREEN"
        state.global_flags -= LOAD_SCREEN
        # Ship the removal now: load_level runs synchronously inside one
        # worker tick, so ed's local send buffer (used once the channel
        # backs up) wouldn't otherwise drain until the whole load returns —
        # main would sit idle and reveal at load-end regardless of the gate.
        Ed.thread_ctx.flush_buffers()
      continue

    if script_name notin script_to_data:
      continue

    let idx = script_to_data[script_name]
    let (thing_id, dir, data_file, _) = loaded_data[idx]
    let unit_started = get_mono_time()

    try:
      var thing: Thing
      if thing_id.starts_with("bot_"):
        thing = data_file.json_to(Bot, opts)
      elif thing_id.starts_with("build_"):
        thing = data_file.json_to(Build, opts)
      else:
        # quit "Unknown thing type: " & thing_id
        error "Unknown thing type", thing_id
        continue

      # Deserialized verbatim from disk: nothing to persist. init_thing
      # marks every thing DIRTY (a script-created unit must save), which
      # made the load-end save re-encode the whole level on a clean boot —
      # seconds of terrain/water encoding in debug for zero changes. A
      # script that genuinely edits during the load re-adds the flag.
      thing.global_flags -= DIRTY
      thing.global_flags += SCRIPT_INITIALIZING
      # script_ctx isn't populated until the thing joins state.things (a worker
      # watch mints it), and we need this before the add — derive the path
      # directly, the same way script_ctx.script does.
      let has_script = file_exists(script_file_for(thing))
      if thing of Build:
        # Publish the persisted voxels into the synced chunk table BEFORE the
        # build joins root_things, so main holds the data the instant it sees
        # the build and the engine prefills each paged-in block (meshed off the
        # main thread) instead of painting it after it loads empty — the
        # terrain's thousands of chunks were painting on main and spiking the
        # load to <1fps.
        Build(thing).reset_bounds
        if has_script:
          # The script runs right after the add; its change_code -> reset()
          # finds the live state already equal to these restored edits and
          # skips the clear+rebuild (see restore_needed).
          Build(thing).restore_edits
          Build(thing).voxels.flush_dirty_chunks()
        else:
          # A scriptless build has no script pass, so do its full
          # restore+draw now: reset() restores+draws into the ASAP buffer,
          # end_asap() flushes it to a mesh. This MUST run BEFORE the add —
          # reset() clears the voxel tables first (voxels.clear()), so running
          # it after the join would wipe the already-published packed_chunks out
          # from under main's prefill (the terrain-goes-missing bug).
          thing.global_flags -= SCRIPT_INITIALIZING
          Build(thing).reset()
          Build(thing).end_asap()
      if parent.is_nil:
        state.things.add(thing)
      else:
        parent.things.add(thing)

      if has_script:
        thing.code = Code.init(read_file(thing.script_ctx.script))

      let took = (get_mono_time() - unit_started).in_milliseconds
      if took > 100:
        info "slow unit load", thing_id, ms = took
      # Keep the stream to main flowing while the load holds the worker
      # (see the PLAYERS step above): drain whatever the channel has room
      # for after each unit instead of dumping everything at load-end.
      Ed.thread_ctx.flush_buffers()
    except Exception as e:
      error "Failed to load thing", thing_id, error = e

  # Record the order the level actually loaded in — including script-less
  # units slotted in above and the PLAYERS sentinel — so save_level preserves
  # it instead of regenerating from scratch.
  if parent.is_nil:
    var final_order: seq[string]
    for script_name in sorted_scripts:
      if script_name == PLAYERS_SENTINEL or
          (script_name in script_to_data and script_name notin final_order):
        final_order.add script_name
    state.load_order = final_order

const
  # Distinctive token present in every managed file's marker, in any format.
  # A file is Enu-managed if it contains this (or doesn't exist yet); the user
  # opts out by deleting the marker. Kept short and shared so the legacy
  # `# AUTOGENERATED` header and the new markdown/JSON markers all match.
  autogenerated_sentinel = "AUTOGENERATED"
  autogenerated_header =
    "# AUTOGENERATED\n# This file is managed by Enu. Delete the line above to manage it yourself.\n"
  autogenerated_md_header =
    "<!-- AUTOGENERATED — managed by Enu. Delete this line to manage it yourself. -->\n"
  autogenerated_json_notice =
    "AUTOGENERATED — managed by Enu. Delete this line to manage this file yourself."
  enu_managed_marker = ".enu_managed"

proc try_write_autogenerated(path, content: string) =
  # Write only if the file is missing or still carries the marker; once the
  # user removes the marker the file is theirs and we leave it alone.
  if file_exists(path) and autogenerated_sentinel notin read_file(path):
    return
  write_file_if_changed(path, content)

proc mcp_bin_path(): string =
  ## Absolute path to the Enu MCP server binary (`bin/enu`), derived from
  ## lib_dir so it tracks the install: dev -> <repo>/bin/enu, dist -> the
  ## `bin/` next to the bundled share.
  let exe = when defined(windows): "enu.exe" else: "enu"
  normalized_path(state.config.lib_dir.parent_dir / "bin" / exe)

proc mcp_json_content(mcp_bin: string): string =
  let node =
    %*{
      "//": autogenerated_json_notice,
      "mcpServers": {
        "enu": {"type": "stdio", "command": mcp_bin, "args": ["mcp"]}
      },
    }
  node.pretty & "\n"

proc settings_local_content(): string =
  # Pre-approve the Enu MCP server so agents (and users) get the tools with no
  # approval prompt — the one bit of provisioning Claude Code requires to be
  # explicit. Skills/commands auto-load straight from .claude/, no plugin.
  let node =
    %*{"//": autogenerated_json_notice, "enabledMcpjsonServers": ["enu"]}
  node.pretty & "\n"

proc save_agent_support(world_dir: string) =
  # Agent scaffolding lives at the world root — the git unit a human or agent
  # opens — not per level. CLAUDE.md — bundled world guide, with the marker
  # prepended.
  let claude_src = state.config.lib_dir / "agent" / "CLAUDE.md"
  if file_exists(claude_src):
    try_write_autogenerated(
      world_dir / "CLAUDE.md", autogenerated_md_header & read_file(claude_src)
    )
  # .mcp.json — Enu MCP server (machine-specific binary path, so gitignored).
  # Skip it when the binary isn't built, rather than write a command that fails.
  let mcp_bin = mcp_bin_path()
  if file_exists(mcp_bin):
    try_write_autogenerated(world_dir / ".mcp.json", mcp_json_content(mcp_bin))
  else:
    debug "Enu MCP binary not found; skipping .mcp.json", path = mcp_bin
  # .claude/ — skills, commands, examples, and MCP auto-approval, managed as a
  # thing: a single `.enu_managed` marker means Enu owns the whole dir and rewrites
  # it wholesale on load; delete the marker to take it over yourself. Skills
  # auto-load from .claude/skills (no plugin/install), commands are namespaced
  # under enu/ (→ /enu:<cmd>), and settings.local.json pre-approves the MCP.
  let claude_dir = world_dir / ".claude"
  if dir_exists(claude_dir) and not file_exists(claude_dir / enu_managed_marker):
    return
  # Build the desired tree first and compare: the old unconditional
  # remove+reseed touched ~40 file mtimes on every boot, defeating change
  # detection over the level dir (the backup manifest).
  var desired = init_table[string, string]()
  desired[enu_managed_marker] = autogenerated_json_notice & "\n"
  desired["settings.local.json"] = settings_local_content()
  let agent_src = state.config.lib_dir / "agent"
  for (src_sub, dst_sub) in [
    ("skills", "skills"), ("commands", "commands" / "enu"),
    ("examples", "examples"),
  ]:
    if dir_exists(agent_src / src_sub):
      for path in walk_dir_rec(agent_src / src_sub, relative = true):
        desired[dst_sub / path] = read_file(agent_src / src_sub / path)

  var unchanged = dir_exists(claude_dir)
  if unchanged:
    var current: HashSet[string]
    for path in walk_dir_rec(claude_dir, relative = true):
      current.incl path
      if path notin desired or read_file(claude_dir / path) != desired[path]:
        unchanged = false
        break
    if unchanged and current.len != desired.len:
      unchanged = false
  if unchanged:
    return

  remove_dir(claude_dir)
  create_dir(claude_dir)
  for rel, contents in desired:
    create_dir(claude_dir / rel.parent_dir)
    write_file(claude_dir / rel, contents)

proc save_ide_support(level_dir: string, sorted_scripts: seq[string]) =
  let imports = sorted_scripts.map_it("import " & it).join("\n")
  try_write_autogenerated(
    level_dir / "project.nim", autogenerated_header & imports & "\n"
  )
  try_write_autogenerated(
    level_dir / "project.nimble",
    autogenerated_header &
      "version = \"0.1.0\"\nauthor = \"Enu\"\ndescription = \"Enu world scripts\"\nlicense = \"MIT\"\nsrcDir = \".\"\nbin = @[\"project\"]\n",
  )
  try_write_autogenerated(
    level_dir / "nim.cfg",
    autogenerated_header & "--path:\"" & state.config.lib_dir / "vmlib" / "enu" &
      "\"\n--path:\"generated\"\n",
  )

proc resolve_world_dir*(work_dir, world: string): string =
  ## A world is always addressed by an absolute path. A relative path — including
  ## a bare world name — resolves from the enu data dir (`work_dir`), never the
  ## process's current directory. The result is normalized and absolute; it's
  ## what gets stored in config.json.
  normalized_path(if is_absolute(world): world else: join_path(work_dir, world))

proc read_world_initial_level*(
    world_dir, lib_dir, world_name: string
): string =
  ## The level named by world.json's `initial_level` — from the world dir if it
  ## has one, else the bundled world of the same name. "" when neither does.
  for dir in [world_dir, lib_dir / "worlds" / world_name]:
    let path = dir / "world.json"
    if file_exists(path):
      try:
        let info = read_file(path).parse_json.json_to(WorldInfo)
        if ?info.initial_level:
          return info.initial_level
      except Exception as e:
        error "Failed to read world.json", path = path, error = e.msg
  ""

proc save_world_info(world_dir, initial_level: string) =
  # world.json is committed, hand-editable authoring metadata: create it once
  # with the current level as the initial level (falling back to "default" when
  # nothing was requested), then never overwrite it. No AUTOGENERATED marker.
  let path = world_dir / "world.json"
  if file_exists(path):
    return
  let info =
    WorldInfo(initial_level: (if ?initial_level: initial_level else: "default"))
  create_dir world_dir
  write_file(path, jsonutils.to_json(info).pretty & "\n")

proc save_world_support*(world_dir: string) =
  ## World-root scaffolding: world.json (create-if-missing), the agent files
  ## (CLAUDE.md, .mcp.json, .claude/), and the single world .gitignore that
  ## covers both the world files and every level's generated artifacts.
  save_world_info(world_dir, state.config.level)
  save_agent_support(world_dir)
  try_write_autogenerated(
    world_dir / ".gitignore",
    autogenerated_header &
      "CLAUDE.md\n.claude/\n.mcp.json\n.gitignore\nbackups/\n" &
      "*/generated/\n*/nim.cfg\n*/project.nim\n*/project.nimble\n",
  )

proc level_json(self: LevelInfo): string =
  # Hand-formatted so start_transform matches the thing files — each basis row
  # and the origin on a single line — rather than std/json's pretty output,
  # which breaks every vector across one-number-per-line.
  let order =
    if self.load_order.len > 0:
      self.load_order.map_it(it.escape_json).join(",\n").indent(4)
    else:
      ""
  let basis =
    self.start_transform.basis.elements.map_it($[it.x, it.y, it.z]).join(",\n")
  let o = self.start_transform.origin
  \"""{{
  "format_version": "{self.format_version}",
  "load_order": [
{order}
  ],
  "show_prototypes": {self.show_prototypes},
  "show_tools": {self.show_tools},
  "start_transform": {{
    "basis": [
{basis.indent(6)}
    ],
    "origin": {$[o.x, o.y, o.z]}
  }}
}}
"""

proc save_level*(level_dir: string, save_all = false, force = false) =
  if (SERVER in state.local_flags and TEST_MODE notin state.local_flags) or force:
    # The whole level is in load_order now — script-less units (terrain and
    # other pure-JSON builds) included, keyed by id. Build the dependency graph,
    # the error set, and the script-less set (all scripted-vs-not decisions key
    # off script_ctx), then order every non-ephemeral unit.
    var graph = initTable[string, seq[string]]()
    var present: seq[string] # every non-ephemeral unit id, in things order
    var is_error = initHashSet[string]()
    var script_less = initHashSet[string]()
    for thing in state.things:
      if EPHEMERAL in thing.global_flags:
        continue
      let name = thing.id
      if name notin present:
        present.add name
      if thing.script_ctx == nil:
        script_less.incl name
      elif thing.errors.value.len > 0:
        is_error.incl name
      elif thing.script_ctx.dependencies.len > 0:
        var deps: seq[string] = @[]
        for dep in thing.script_ctx.dependencies:
          let dep_name = dep.extract_filename
          deps.add(
            if dep_name.ends_with(".nim"): dep_name[0 .. ^5] else: dep_name
          )
        graph[name] = deps

    # The PLAYERS sentinel is the spawn gate, and it's a hard partition: units
    # before it are the pre-reveal set, units after stream in behind the player.
    # Keep every unit on the side it's already on so the sentinel never drifts —
    # a non-gating level (PLAYERS first) stays non-gating. New units append to a
    # side: script-less ones join the gate set only when the level already
    # gates; scripted ones always land after. Errors and topo ordering happen
    # within a side, so a transiently-broken unit can't jump ahead of PLAYERS.
    let gate_idx = state.load_order.find(PLAYERS_SENTINEL)
    let gating = gate_idx > 0
    var pre, post: seq[string]
    var seen = initHashSet[string]()
    for i, name in state.load_order:
      if name == PLAYERS_SENTINEL or name notin present or name in seen:
        continue
      seen.incl name
      if gate_idx >= 0 and i < gate_idx:
        pre.add name
      else:
        post.add name
    for name in present:
      if name in seen:
        continue
      seen.incl name
      if gating and name in script_less:
        pre.add name
      else:
        post.add name

    proc ordered(side: seq[string]): seq[string] =
      # Errored units keep their given order — excluded from the graph sort to
      # dodge circular-dependency blowups — ahead of the topo-sorted rest.
      var errs, rest: seq[string]
      for name in side:
        if name in is_error:
          errs.add name
        else:
          rest.add name
      errs & topo_sort(rest, graph)

    var sorted_scripts: seq[string]
    try:
      sorted_scripts = ordered(pre) & @[PLAYERS_SENTINEL] & ordered(post)
      debug "saving level sorted scripts", scripts_len = sorted_scripts.len
    except ValueError as e:
      error "Cannot save level script order due to circular dependency",
        error = e.msg
      sorted_scripts = pre & @[PLAYERS_SENTINEL] & post # fallback: unordered
    state.load_order = sorted_scripts

    if sorted_scripts.len > 0:
      debug "load_order content", load_order = sorted_scripts

    let level = LevelInfo(
      format_version: "1.0.0",
      load_order: sorted_scripts,
      show_prototypes: state.show_prototypes,
      show_tools: state.show_tools,
      start_transform: state.start_transform,
    )
    write_file_if_changed level_dir / "level.json", level.level_json
    save_ide_support(level_dir, sorted_scripts)
    save_world_support(state.config.world_dir)

    for thing in state.things:
      if EPHEMERAL in thing.global_flags:
        continue
      if save_all or DIRTY in thing.global_flags:
        thing.save
        if ?thing.script_ctx:
          try:
            thing.script_ctx.last_saved_json_mtime =
              get_last_modification_time(thing.data_file)
          except OSError:
            discard
        thing.global_flags -= DIRTY
  else:
    debug "not server. Skipping save."

type LevelBackup = object
  ## Everything the deflate thread needs — the archive is built (files
  ## read) on the worker, so the snapshot can't race a concurrent save
  ## (saves run on the worker too). The thread touches no game state.
  archive: ZipArchive
  dest: string
  manifest: string
  manifest_path: string
  prune_glob: string

var backup_thread {.threadvar.}: system.Thread[LevelBackup]
var backup_thread_started {.threadvar.}: bool
var live_backup {.threadvar.}: LevelBackup
  ## Worker-side reference to the in-flight payload. create_thread's arg
  ## shares the archive REF with the thread; without a reference alive on
  ## this side, ORC reclaims it under the compressor and the backup dies
  ## silently. Cleared after the join.

proc backup_write(payload: LevelBackup) {.thread.} =
  ## Compress and write the backup off the worker thread — deflating the
  ## island's ~50 MB froze the worker for ~10s in debug builds (visible as
  ## every animation in the world stopping). Prune and record the manifest
  ## only after a successful write, so a failed or interrupted backup is
  ## retried in full next time.
  try:
    payload.archive.write_zip_archive(payload.dest)
    write_file(payload.manifest_path, payload.manifest)
    let backups = walk_files(payload.prune_glob).to_seq.sorted
    if backups.len > 19:
      for file in backups[0 ..^ 20]:
        remove_file file
  except CatchableError as e:
    stderr.write_line "level backup failed: " & e.msg

proc finish_backup*() =
  ## Join an in-flight backup so a normal quit can't truncate it.
  if backup_thread_started:
    join_thread(backup_thread)
    backup_thread_started = false
    live_backup = LevelBackup()

proc backup_level*(level_dir: string) =
  ## Snapshot the level into backups/<level>_<timestamp>.zip — insurance
  ## against Enu bugs that destroy level data, so it must capture the state
  ## BEFORE Enu writes (the boot call runs ahead of load_level, which saves
  ## at its end). Skipped when nothing changed since the last backup (the
  ## manifest), so idle sessions cost nothing; the heavy compression runs
  ## on its own thread (see backup_write).
  if SERVER notin state.local_flags:
    return
  if backup_thread_started:
    if backup_thread.running:
      # previous backup still compressing; the next interval retries
      return
    finish_backup()
  if not dir_exists(level_dir):
    return

  let backup_dir = state.config.world_dir / "backups"
  create_dir backup_dir

  var lines: seq[string]
  for path in walk_dir_rec(level_dir, relative = true):
    let full = level_dir / path
    try:
      lines.add path & "|" & $get_last_modification_time(full).to_unix & "|" &
        $get_file_size(full)
    except OSError:
      discard
  if lines.len == 0:
    return
  lines.sort
  let manifest = lines.join("\n")
  let manifest_path = backup_dir / state.config.level & ".manifest"
  try:
    if file_exists(manifest_path) and read_file(manifest_path) == manifest:
      return # unchanged since the last backup
  except IOError:
    discard

  let archive = ZipArchive()
  archive.add_dir(level_dir)
  live_backup = LevelBackup(
    archive: archive,
    dest:
      backup_dir / state.config.level & "_" &
      times.now().format("yyyy-MM-dd-HH-mm-ss") & ".zip",
    manifest: manifest,
    manifest_path: manifest_path,
    prune_glob: backup_dir / state.config.level & "_????-??-??-??-??-??.zip",
  )
  backup_thread_started = true
  info "backing up level", dest = live_backup.dest
  backup_thread.create_thread(backup_write, live_backup)

proc load_user_config*(dir = ""): UserConfig =
  var work_dir = dir
  if not ?dir:
    work_dir = state.config.work_dir
  let config_file = join_path(work_dir, "config.json")
  if file_exists(config_file):
    let opt = Joptions(allow_missing_keys: true, allow_extra_keys: true)
    try:
      result.from_json(read_file(config_file).parse_json, opt)
    except Exception as e:
      error "Failed to load user config", error = e
  # `world` is stored as an absolute path. Normalize any saved value (and any
  # legacy bare name, which meant a world under the enu data dir) to an absolute
  # path so world_dir is unambiguous from here on.
  if ?result.world and ?result.world.get:
    result.world = some(resolve_world_dir(work_dir, result.world.get))

proc build_user_config*(config: Config): UserConfig =
  for config_name, config_field in config.field_pairs:
    for user_name, user_field in result.field_pairs:
      when config_name == user_name:
        user_field = some(config_field)
  # config.world is the world *name*; config.json stores the world *path*.
  result.world = some(config.world_dir)

proc save_user_config*(config: UserConfig) =
  let
    work_dir = state.config.work_dir
    config_file = join_path(work_dir, "config.json")
  write_file(config_file, jsonutils.to_json(config).pretty)

proc change_loaded_level*(level, world: string) =
  var config = state.config
  # `world` may be a full path (an explicit world dir) or a relative path / bare
  # name (resolved from the enu data dir). Resolve to an absolute path so
  # world_dir stays authoritative — switching levels must never re-root an
  # out-of-work_dir world back under the work dir. The world *name* is always the
  # path's final component.
  let world_dir = resolve_world_dir(config.work_dir, world)
  config.world_dir = world_dir
  config.world = world_dir.last_path_part
  config.level = level
  state.level_name = config.world & "/" & config.level
  config.level_dir = join_path(world_dir, level)
  state.config = config

proc run_state_initializers*(worker: Worker) =
  # Re-establish VM-side globals (players.nim's `player`, etc.) registered via
  # register_state_init. Must run after every interpreter rebuild before any
  # thing script executes — thing scripts reference `player` at top level.
  let init_proc =
    worker.interpreter.select_routine("initialize_state", "core")

  assert not init_proc.is_nil,
    "initialize_state routine not found in core module. " &
      "Ensure core defines and exports initialize_state()."

  # Set player as active thing so VM hooks work correctly during initialization
  assert worker.active_thing.is_nil, "active_thing should be nil at this point"
  worker.active_thing = state.player
  state.player.script_ctx.fuel = script_fuel

  try:
    {.gcsafe.}:
      discard worker.interpreter.call_routine(init_proc, [])
  except VMQuit as e:
    state.err(e.msg)

  worker.active_thing = nil

proc unload_level*(worker: Worker) =
  state.global_flags += LOADING_LEVEL
  state.push_flag LOADING_SCRIPT
  state.pop_flag PLAYING
  state.things.clear_all
  state.pop_flag LOADING_SCRIPT
  state.global_flags -= LOADING_LEVEL
  state.global_flags -= LOAD_SCREEN

var level_loading* = false
  ## True while load_level populates things. watch_code's autosave consults
  ## this: the loader assigning each unit's code was triggering a full
  ## save_level (frame re-encodes included) synchronously inside the load —
  ## most of a debug build's 5-10s boot penalty.

proc load_level*(worker: Worker, level_dir: string) =
  level_loading = true
  defer:
    level_loading = false
  if not state.player.is_nil:
    state.player.block_log_entries.clear
  var config = state.config

  config.level_dir = level_dir
  config.data_dir = join_path(config.level_dir, "data")
  config.script_dir = join_path(config.level_dir, "scripts")

  let level_file = level_dir / "level.json"

  if not file_exists(level_file):
    let
      # Bundled templates are keyed by the world's last path segment (its name),
      # so this resolves the source even when the world is an arbitrary path.
      base = config.lib_dir / "worlds" / config.world_dir.last_path_part
      level = base / config.level
      tmpl = base / "template"

    if dir_exists(level):
      copy_dir(level, config.level_dir)
    elif dir_exists(config.world_dir / "template"):
      copy_dir(config.world_dir / "template", config.level_dir)
    elif dir_exists(tmpl):
      copy_dir(tmpl, config.level_dir)

  create_dir(config.data_dir)
  create_dir(config.script_dir)

  debug "loading ", level_file
  var load_order = newSeq[string]()

  state.show_prototypes = true
  state.show_tools = true
  state.start_transform = Transform.init(origin = vec3(0, 1, 0))
  if file_exists(level_file):
    try:
      let level_json = read_file(level_file)
      let level = level_json.parse_json.json_to(LevelInfo)
      if level.load_order.len > 0:
        load_order = level.load_order
      state.show_prototypes = level.show_prototypes
      state.show_tools = level.show_tools
      state.start_transform = level.start_transform
    except Exception as e:
      error "Failed to load level", error = e

  # The spawn gate: everything before PLAYERS in load_order must render
  # before players get control. Missing sentinel = front = nothing to wait
  # for (immediate physics, no splash). Raise the splash-phase signal only
  # when there really are units ahead of the gate; load_things clears it at
  # the PLAYERS step.
  #
  # LOAD_SCREEN must be raised BEFORE LOADING_LEVEL: main hands the splash
  # to the gate the moment either load flag lands, and holds it only if
  # SPAWN_HELD is up — which its LOAD_SCREEN watch pushes. Raised in this
  # order they ship in one batch and apply in order; raised after (the old
  # entry-time LOADING_LEVEL push, then seconds of level seeding/parsing
  # before this point) LOADING_LEVEL could land a batch early and flash a
  # frame of the empty 3D scene between the boot splash and the gate.
  if PLAYERS_SENTINEL notin load_order:
    load_order.insert(PLAYERS_SENTINEL, 0)
  if load_order.find(PLAYERS_SENTINEL) > 0:
    state.global_flags += LOAD_SCREEN
  state.global_flags += LOADING_LEVEL
  state.push_flag LOADING_SCRIPT
  state.config = config

  # Carry every player to the spawn pose now, not at the PLAYERS step: they
  # are frozen behind the splash anyway, and the voxel viewer follows them —
  # so the chunks around the spawn stream at top priority for the whole load
  # instead of racing the reveal from 200m away.
  block:
    let t = state.start_transform
    let rotation =
      rad_to_deg(arctan2(t.basis.elements[0].z, t.basis.elements[0].x))
    for thing in state.things:
      if thing of Player:
        let player = Player(thing)
        player.transform = t
        player.rotation = rotation

  # Seed the available tools before scripts run and the player can interact:
  # full set by default, empty when the level opts out (its script adds back
  # what it needs). Happens inside LOADING_LEVEL so the toolbar snaps, no slide.
  if state.show_tools:
    state.tools.value = {CODE_MODE .. PLACE_BOT}
  else:
    state.tools.clear()

  # Ship the load-start decision to main before any unit loads. A gated level
  # (LOAD_SCREEN up) holds the splash through the gate; an ungated one (PLAYERS
  # first, no LOAD_SCREEN) has nothing to wait on, so main drops the splash here
  # — before the first unit — rather than only once it happens to observe
  # LOADING_LEVEL mid-load. The players are already at the spawn pose above, so
  # the world simply streams in behind a settled camera.
  Ed.thread_ctx.flush_buffers()

  worker.run_state_initializers()

  dont_join = true
  worker.retry_failures = true
  load_things(nil, load_order)

  worker.retry_failed_scripts()
  worker.retry_failures = false
  dont_join = false

  # Save after retry so the load_order and any script-resolved deps are
  # captured. save_all=false: only things dirtied during the load are
  # rewritten, not every unit unconditionally. (thing.save already skips
  # unchanged files by content, so this is a small win — but forcing writes
  # churned mtimes and disk on every clean boot for no reason.)
  save_level(state.config.level_dir, save_all = false)

  for thing in state.things:
    thing.global_flags -= DIRTY
  state.pop_flag LOADING_SCRIPT
  state.global_flags -= LOADING_LEVEL
  # Normally cleared at the PLAYERS step in load_things; this is a safety net
  # for a load that died before reaching it, so the splash can't stick.
  state.global_flags -= LOAD_SCREEN
